### PR TITLE
Jdk 19 ea

### PR DESCRIPTION
**Pull request by mklaehn**

### CODE REVIEW

**Comment by mklaehn** [comment]
Our used groovy version appear unable to cope with JDK19 class files.
PR #1114 attempts to fix this by bumping to Groovy version 4

**Comment by mklaehn** [comment]
Okay. So the groovy version was not the only problem. It appears that gradle 7.4.x is not yet java 19 compatible. Gradle however provides support for toolchains. Some more work todo

**Comment by reinhapa** [comment]
> Okay. So the groovy version was not the only problem. It appears that gradle 7.4.x is not yet java 19 compatible. Gradle however provides support for toolchains. Some more work todo

@mklaehn you could try if the upcoming Gradle version (7.5-rc-1) may support it...

**Comment by mklaehn** [comment]
> > Okay. So the groovy version was not the only problem. It appears that gradle 7.4.x is not yet java 19 compatible. Gradle however provides support for toolchains. Some more work todo
> 
> @mklaehn you could try if the upcoming Gradle version (7.5-rc-1) may support it...

@reinhapa yes I mighgt. But waiting for the next gradle version just to use the  next jdk ea version does not sound like a feasible solutio longterm.

From what I've read about this current problem it  is suggested by gradle staff to use the toolchain support. as gradle itself does not require jdk 19 in order to compile with jdk 19.

**Review by svenreimers — APPROVED** [review]

**Pull request merged**
