### PR TITLE
Updates Gradle to 6.3 and a lot of libraries

### PR DESCRIPTION
**Pull request by reinhapa**
Summary of changed versions:

library reference|old version|new version
-----------------|-----------|-----------
versionGoogleVision|1.99.1|1.99.3
versionGradleBintrayPlugin|1.8.4|1.8.5
versionGradleInfoPlugin|5.2.0|7.1.3
versionGradleVersionsPlugin|0.27.0|0.28.0
versionJavaActivation|1.2.0|1.2.2
versionJaxB|2.4.0-b+|2.3.3
versionJaxBruntime|-|2.3.2
versionJersey|2.29.1|2.30.1
versionJGit|5.+|5.7.0.202003110725-r
versionJUnit|4.12|4.13
versionLog4j|2.13.0|2.13.1
versionNebulaPublishingPlugin|14.1.1|17.2.1
versionSonarqubeGradlePlugin|2.8|2.8.0.1969
versionSpotless|3.25.0|3.28.1
versionYasson|1.0.5|1.0.6

### CODE REVIEW

**Comment by reinhapa** [comment]
@svenreimers still draft, as I fixed all compile dependencies with latest library versions. Still spotless failures, where I do not have a idea, what the action to take would be...

**Comment by svenreimers** [comment]
Suggestion: Split in multiple PR's
- Gradle 7.4.1
- Jakarta EE
- Other Gradle Plugin Updates
- Other compile  time and runtime updates
WDYT @reinhapa @mklaehn ?

**Comment by mklaehn** [comment]
Seeing that the upgrade to Gradle 7.4.1 requires quite a few changes in and of itself it might be advisable to do that as a standalone change.
The other changes should not require such widespread changes - not that they will be small.

**Comment by reinhapa** [comment]
> Suggestion: Split in multiple PR's
> 
>     * Gradle 7.4.1
>     * Jakarta EE
>     * Other Gradle Plugin Updates
>     * Other compile  time and runtime updates
>       WDYT @reinhapa @mklaehn ?

@svenreimers @mklaehn you can use my PR to split up.

**Comment by mklaehn** [comment]
thanks and sorry for the inconvenience

**Comment by reinhapa** [comment]
at least it can be a hint for the changes to be made...

**Comment by mklaehn** [comment]
I think I have most - if not all - changes you proposed integrated into the master branch. Maybe even some additions from libraries that have had their maven coordinates changed (spotbugs if I remember correctly).

Work is ongoing reenabling some tasks/checks I've had to disable to get the build to finish. Javadoc for some reasons breaks apart completely. Spotbugs has enhanced some checks for mutable object detection.

Apart from that master branch is compilable with JDK 17 and 18-ea with gradle 7.4.1 and we are up-to-date again. Also Dependabot is configured so it should be easier to stay updated apart from apart from updates to gradle itself.

**Pull request closed without merging**
